---
  - hosts: zabbix
    user: vagrant
    sudo: yes
    tasks:
      - name: Install pip
        yum: name=python-pip state=installed
      - name: install zabbix-api
        pip: name=zabbix-api state=present
      - name: Create host groups
        zabbix_group:
           server_url=http://192.168.22.14/zabbix
           login_user=Admin
           login_password=zabbix
           state=present
           host_group=Examplgroup1
#              - Examplegroup2
#        when: inventory_hostname==groups['group_name'][0:wq]

