---
- name: Install MySQL
  yum: name={{ item }} state=present
  with_items:
  - mariadb-server
  - MySQL-python

- name: Start MySQL Server
  service: name=mariadb state=started enabled=yes

- name: update mysql root password for all root accounts
  mysql_user: name=root host={{ item }} password={{ root_db_password }}
  with_items:
  - 127.0.0.1
  - ::1
  - localhost

- name: copy .my.cnf file with root password credentials
  template: src=my.cnf.j2 dest=/root/.my.cnf owner=root mode=0600

- name: Add user 056db
  mysql_user: name=056db password=056db host=localhost state=present

- name: Create table
  mysql_db: name=omsdb state=present

- name: config
  mysql_user: name=056db password=056db priv=omsdb.*:ALL,GRANT state=present host=localhost
  notify: restart mysql