---
  - hosts: zabbix-agent
    user: vagrant
    sudo: yes
    tasks:
     - name: Install Zabbix Repository Key 
       rpm_key: state=present key=http://repo.zabbix.com/RPM-GPG-KEY-ZABBIX
     - name: Install Zabbix Repository and other packages needed by Ansible
       yum: pkg=http://repo.zabbix.com/zabbix/2.4/rhel/7/x86_64/zabbix-release-2.4-1.el7.noarch.rpm state=installed
