---
  - hosts: zabbix
#    roles:
#      - zabbix-server
    user: vagrant
    sudo: yes
    tasks:
     - name: Install ntp
       yum: name=ntp state=installed
     - name: run ntp
       service: name=ntpd state=started enabled=yes
     
     - name: Install Apache server
       yum: name=httpd state=installed
     - name: start Apache server
       service: name=httpd state=started enabled=yes
     - name: Install Zabbix Repository Key 
       rpm_key: state=present key=http://repo.zabbix.com/RPM-GPG-KEY-ZABBIX

     - name: Install Zabbix Repository and other packages needed by Ansible
       yum: pkg={{item}} state=installed  
       with_items:
         - policycoreutils-python
         - libselinux-python
         - MySQL-python
         - http://repo.zabbix.com/zabbix/2.4/rhel/7/x86_64/zabbix-release-2.4-1.el7.noarch.rpm
 



#     - name: Install MySQL(mariadb)
#       yum: name ={{item}} state=installed
#       with_items:
#         - mariadb-server
#         - zabbix-server-mysql
#         - zabbix-web-mysql
#         - zabbix-agent
#         - mysql
#         - php 
#   
#


#    - name: install Zabbix repo for CentOS7
#      template: src=zabbix.repo.j2
#                dest=/etc/yum.repos.d/zabbix.repo
#                owner=root
#                group=root
#                mode=0644
#      when: zabbix_repo
