---
  - hosts: zabbix-agent
    user: vagrant
    sudo: yes
    tasks:
     - name: Install Zabbix Repository and other packages needed by Ansible
       yum: pkg=http://repo.zabbix.com/zabbix/2.4/rhel/7/x86_64/zabbix-release-2.4-1.el7.noarch.rpm state=installed
     - name: Install zabbix agent
       yum: name=zabbix-agent state=installed
     - name: Run zabbix agent
       service: name=zabbix-agent state=started enabled=yes

#      - #name: COnfig zabbix agent
 #       #template: src=zabbix_agentd.j2
 #       #          dest=/etc/zabbix/zabbix_agentd.conf

